var files = {
	"Content Demos": [
		"Depth-AmpRoom-M1DualLayer",
		"Depth-AmpRoom-M1+Object",
		"Depth-Glados-M1DualLayer",
		"Depth-Jazz-M1DualLayer",
		"Music-LiveShow",
		"Music-Electronic",
		"Music-LiveShow2",
		"Music-Piano",
		"Recording-Cheetah",
		"Recording-TibetanBowls",
		"Recording-Chinatown",
		"Recording-Clock",
		"Recording-Drummers",
		"Recording-Monk",
		"Recording-Hippo",
		"SoundDesign-BinauralQ",
		"SoundScene-Okavango",
		"SoundScene-Titanic",
	],
	"Web Implementation Examples": [
		"Facetracking-SpatialPlayer",
		"Mach1Encode-Example-Web",
		"Mach1Encode-RenderFileExample-Web",
		"Mach1Decode-360VideoPlayer",
	],
	"Mobile Implementation Examples": [
		"Mach1Encode-Example-iOS",
		"BoseAR-Mach1SpatialAudioPlayer-iOS",
		"Mach1Encode-Example-Android",
	],
	"Utilities": [
		"Mach1React-Test",
	]
};

var tags = {
	"Depth-AmpRoom-M1DualLayer": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"Depth-AmpRoom-M1+Object": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"Depth-Glados-M1DualLayer": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"Depth-Jazz-M1DualLayer": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"Music-Electronic": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"Music-LiveShow": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"Music-LiveShow2": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"Music-Piano": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"Recording-Clock": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"Recording-Cheetah": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"Recording-Monk": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"Recording-TibetanBowls": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"Recording-Chinatown": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"Recording-Drummers": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"Recording-Hippo": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"SoundDesign-BinauralQ": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"SoundScene-Okavango": [ "sound scene", "facetracking", "device", "mouse", "mach1decode" ],
	"SoundScene-Titanic": [ "sound scene", "facetracking", "device", "mouse", "mach1decode" ],
	"Ambience-1": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"Ambience-2": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"Ambience-3": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"Ambience-4": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"Ambience-5": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"Facetracking-SpatialPlayer": [ "facetracking", "device", "mouse", "mach1decode" ],
	"Mach1Encode-Example-Web": [ "mouse", "mach1encode", "mach1decode" ],
	"Mach1Encode-RenderFileExample-Web": [ "mouse", "mach1encode", "mach1decode" ],
	"Mach1Decode-360VideoPlayer": [ "mouse", "video", "mach1decode" ],
	"Mach1Encode-Example-iOS": [ "cocoapods", "mach1encode", "mach1decode" ],
	"BoseAR-Mach1SpatialAudioPlayer-iOS": [ "cocoapods", "mach1encode", "mach1decode" ],
	"Mach1Encode-Example-Android": [ "touch", "mach1encode", "mach1decode" ],
	"Mach1React-Test": [ "library-test", "mach1encode", "mach1decode", "mach1decodepositional", "mach1transcode" ]
};
