var files = {
	"content demos": [
		"depth-amproom-m1duallayer",
		"depth-amproom-m1+object",
		"depth-glados-m1duallayer",
		"depth-jazz-m1duallayer",
		"music-liveshow",
		"music-electronic",
		"music-liveshow2",
		"music-piano",
		"recording-cheetah",
		"recording-tibetanbowls",
		"recording-chinatown",
		"recording-clock",
		"recording-drummers",
		"recording-monk",
		"recording-hippo",
		"sounddesign-binauralq",
		"soundscene-okavango",
		"soundscene-titanic",
	],
	"web implementation examples": [
		"facetracking-spatialplayer",
		"mach1encode-example-web",
		"mach1encode-renderfileexample-web",
		"mach1decode-360videoplayer",
	],
	"mobile implementation examples": [
		"mach1encode-example-ios",
		"bosear-mach1spatialaudioplayer-ios",
		"mach1encode-example-android",
	],
	"utilities": [
		"mach1react-test",
	]
};

var tags = {
	"depth-amproom-m1duallayer": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"depth-amproom-m1+object": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"depth-glados-m1duallayer": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"depth-jazz-m1duallayer": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"music-electronic": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"music-liveshow": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"music-liveshow2": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"music-piano": [ "music", "facetracking", "device", "mouse", "mach1decode" ],
	"recording-clock": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"recording-cheetah": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"recording-monk": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"recording-tibetanbowls": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"recording-chinatown": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"recording-drummers": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"recording-hippo": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"sounddesign-binauralq": [ "sound design", "facetracking", "device", "mouse", "mach1decode" ],
	"soundscene-okavango": [ "sound scene", "facetracking", "device", "mouse", "mach1decode" ],
	"soundscene-titanic": [ "sound scene", "facetracking", "device", "mouse", "mach1decode" ],
	"ambience-1": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"ambience-2": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"ambience-3": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"ambience-4": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"ambience-5": [ "ambience", "facetracking", "device", "mouse", "mach1decode" ],
	"facetracking-spatialplayer": [ "facetracking", "device", "mouse", "mach1decode" ],
	"mach1encode-example-web": [ "mouse", "mach1encode", "mach1decode" ],
	"mach1encode-renderfileexample-web": [ "mouse", "mach1encode", "mach1decode" ],
	"mach1decode-360videoplayer": [ "mouse", "video", "mach1decode" ],
	"mach1encode-example-ios": [ "cocoapods", "mach1encode", "mach1decode" ],
	"bosear-mach1spatialaudioplayer-ios": [ "cocoapods", "mach1encode", "mach1decode" ],
	"mach1encode-example-android": [ "touch", "mach1encode", "mach1decode" ],
	"mach1react-test": [ "library-test", "mach1encode", "mach1decode", "mach1decodepositional", "mach1transcode" ]
};
